### PR TITLE
freebsd: teach rebar how to find ports tree dependencies

### PR DESCRIPTION
**Pull request by dch**
rebar.config needs FreeBSD include & lib paths added to locate `expat.h` from the xml package.

### CODE REVIEW

**Comment by dch** [comment]
this appears only to be a solution when built with rebar/rebar3, when used via mix the parameters aren't passed through. Maybe @polymetis has a better approach?

**Comment by polymetis** [comment]
Okay. So this is a bit of a cacophonic pull-request but it is based on some discussion.

So, why are we suddenly deleting mix things. 

Basically we wanted to build fastxml on a FreeBSD machine as part of an elixir app. I won't go into into the nitty gritty of what we tried but basically it boils down to. 

 - Getting Rebar3 to compile the app is quite simple (https://github.com/processone/fast_xml/pull/14/commits/2f91d73318503ac98cd6acae534db5dccdecdbe7)
 - FreeBSD has a different version of make by default (not gmake, I think it's make.inc but don't quote me. That's more @dch 's thing)
 - Mix be default can just compile a rebar3 project if it doesn't have a mix.exs file. (This works nicely with tools like Distillery and legacy Exrm) 
 - And we can just publish with rebar3 to hex.pm. (https://hex.pm/docs/rebar3_publish)

However 

We didn't want to overstep our bounds and change the way that you publish the package. We wondering if you want us to lay in the ground work to turn fastxml into a pure rebar3 project?

**Comment by dch** [comment]
bump - we'd like to get this merged in, any comments?

**Comment by dch** [comment]
closed in favour of new PR with conflicts resolved - https://github.com/processone/fast_xml/pull/22

**Pull request closed without merging**
